Feature/Added prop for passing function when close button is clicked
fkhadra/react-toastify pull request #1118
Opened 2024-05-20 15:53 UTC by sbsangu

### Fixes

- Fixes #1117 

### Summary

Added an `onButtonClose` prop to the `Toast` component to allow users to define a callback function that gets called when the close button of a toast is clicked. This enhancement improves the flexibility and usability of the toast component by allowing custom behavior to be executed when the close button is pressed.

### Changes

- Updated the `Toast` component to accept and handle a new `onButtonClose` prop.
- Updated the `ToastContainer` component to pass the `onButtonClose` prop to each `Toast` component.
- Updated TypeScript definitions to include the new `onButtonClose` prop.

### Checklist

- [x] Forked the repository and created a new branch from `master`.
- [x] Ran `yarn` in the repository root.
- [x] Added tests to cover the new functionality.
- [x] Ensured the test suite passes (`yarn test`).
- [x] Ran `yarn start` to test changes in the playground.
- [x] Updated the readme if needed.
- [x] Updated the TypeScript definitions if needed.
- [x] Formatted the code with [prettier](https://github.com/prettier/prettier) (`yarn prettier-all`).
- [x] Ensured the code lints (`yarn lint:fix`).

### Additional Information

This feature allows users to pass a callback function that will be called when the toast's close button is clicked, enabling more custom and dynamic behaviors when a toast is dismissed.

2024-05-25 20:46 UTC, CalvinJamesHeath requested changes
Excellent!

2024-05-26 04:17 UTC, sbsangu commented
Could you please let me know if this pull request resolves the issue? 
Additionally, do you think it is ready to be merged?

2024-06-07 21:13 UTC, zizhengtai requested changes

2024-06-07 21:13 UTC, zizhengtai commented on README.md
> +### ToastContainer Props
I don't think this should be added here, the README seems to contain only high-level information about the project and not detailed release notes.

2024-06-07 21:13 UTC, zizhengtai commented on package-lock.json
Can we delete this? The project is not using package-lock.json.

2024-06-07 21:13 UTC, zizhengtai commented on yarn.lock
Can you revert these changes? There doesn't seem to be any good reason for it.

2024-07-07 20:20 UTC, closed without merging